### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bnjmnt4n** [dbrgn/heroku-buildpack-python-sklearn#10]
Hi, I'm trying to build a Heroku app which uses matplotlib. According to your README, I should see something like this:

```
-----> Noticed numpy/scipy. Bootstrapping prebuilt binaries.
-----> Creating/downloading binaries.
-----> Creating/downloading numpy bdist.
-----> Creating/downloading scipy bdist.
```

However in my [build](https://travis-ci.org/wei2912/bce-simulation/builds/25394450), as far as I can tell they are actually building numpy from scratch. I'm not really good with Python, and it would be great if you could advise me.

**Comment by dbrgn** [comment]
I never tried deploying via Travis, but if you put your Heroku API_KEY in a public repository, won't it be possible for anyone to deploy malicious apps to your Heroku account?

And regarding the deployment itself, it doesn't look like you're setting the buildpack url. You need to change the deployment somehow (don't know how it works on Travis) to use this repository as buildpack instead of the default.

**Comment by bnjmnt4n** [comment]
Nope, Travis has secure environment variables, encrypted so that only your builds can have them.

I've already set the buildpack URL using heroku on my local machine. I'm using multi-buildpack to add the default node.js buildpack and this one. I'm retrying the build now, hope it works !

**Comment by bnjmnt4n** [comment]
Do you have a git SHA where the buildpack was known to be working? Perhaps there's an issue with master.

**Comment by dbrgn** [comment]
I just tested the demo again (https://github.com/dbrgn/heroku-buildpack-python-sklearn#demo), and everything works fine.

**Comment by bnjmnt4n** [comment]
You're right, there was an issue with my buildpack. It's now been fixed.
Thanks for your help anyway ;)

**Comment by dbrgn** [comment]
And in the future, you should use this buildpack, as I'm not maintaining my fork anymore: https://github.com/thenovices/heroku-buildpack-scipy
